import type { Product } from '@/components/ui/ProductCard';

export const SPECIAL_PRODUCT_DATA: Product[] = [
    {
        id: 1,
        status: 'selling',
        type: 'special',
        thumbnails: ['/images/product/product-1-1.jpg', '/images/product/product-1-2.jpg', '/images/product/product-1-3.jpg', '/images/product/product-1-4.jpg', '/images/product/product-1-5.jpg'],
        tagImage: '/images/tag/living-fair.png',
        title: '메디니스/핫슘/라오메뜨 외 건강용품 특집건강용품 특집건강용품 특집',
        price: 109000,
        discount: 10,
        purchases: 33584,
        likes: 100,
        flags: ['broadcast', 'delivery'],
        benefits: [
            { type: 'coupon', value: '10%' },
            { type: 'card', value: '무이자3' },
        ],
    },
    {
        id: 2,
        status: 'selling',
        type: 'special',
        thumbnails: ['/images/product/product-1-1.jpg', '/images/product/product-1-2.jpg', '/images/product/product-1-3.jpg', '/images/product/product-1-4.jpg', '/images/product/product-1-5.jpg'],
        tagImage: '/images/tag/luxury.png',
        title: '메디니스/핫슘/라오메뜨 외 건강용품 특집',
        price: 109000,
        discount: 50,
        purchases: 33584,
        likes: 340,
        flags: ['broadcast', 'tomorrow', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '50%' }],
    },
    {
        id: 3,
        status: 'selling',
        type: 'special',
        thumbnails: ['/images/product/product-1-1.jpg', '/images/product/product-1-2.jpg', '/images/product/product-1-3.jpg', '/images/product/product-1-4.jpg', '/images/product/product-1-5.jpg'],
        title: '메디니스/핫슘/라오메뜨 외 건강용품 특집',
        price: 109000,
        purchases: 33584,
        likes: 77,
        flags: ['broadcast', 'weekend', 'delivery', 'return'],
    },
];

export const PRODUCT_DATA: Product[] = [
    {
        id: 4,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        stars: 4.7,
        reviews: 118,
        flags: ['broadcast', 'weekend', 'delivery', 'return'],
        benefits: [{ type: 'card', value: '무이자3' }],
    },
    {
        id: 5,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 45,
        stars: 4.7,
        reviews: 550,
        flags: ['broadcast', 'tomorrow', 'delivery', 'return'],
        benefits: [
            { type: 'coupon', value: '45%' },
            { type: 'card', value: '무이자3' },
        ],
    },
    {
        id: 6,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 5,
        stars: 2.5,
        reviews: 5,
        flags: ['broadcast', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '5%' }],
    },{
        id: 7,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 5,
        stars: 2.5,
        reviews: 5,
        flags: ['broadcast', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '5%' }],
    },{
        id: 8,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 5,
        stars: 2.5,
        reviews: 5,
        flags: ['broadcast', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '5%' }],
    },{
        id: 9,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 5,
        stars: 2.5,
        reviews: 5,
        flags: ['broadcast', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '5%' }],
    },{
        id: 10,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 5,
        stars: 2.5,
        reviews: 5,
        flags: ['broadcast', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '5%' }],
    },{
        id: 11,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 5,
        stars: 2.5,
        reviews: 5,
        flags: ['broadcast', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '5%' }],
    },{
        id: 12,
        status: 'selling',
        type: 'product',
        brand: '바니스뉴욕',
        thumbnails: ['/images/product/product-2.jpg'],
        title: '[최초가169,000원] 이반프린지 셔츠 원피스',
        price: 129000,
        discount: 5,
        stars: 2.5,
        reviews: 5,
        flags: ['broadcast', 'delivery', 'return'],
        benefits: [{ type: 'coupon', value: '5%' }],
    },
];

export const CONSULTATION_PRODUCT_DATA: Product[] = [
    {
        id: 7,
        status: 'selling',
        brand: '한샘',
        type: 'consultation',
        thumbnails: ['/images/product/product-3.jpg'],
        title: '이지홈 인테리어',
        flags: ['broadcast'],
    },
    {
        id: 8,
        status: 'selling',
        brand: '노랑풍선',
        type: 'consultation',
        thumbnails: ['/images/product/product-3.jpg'],
        title: '큐슈 3일 #온천여행 #가을단풍',
        flags: ['broadcast'],
    },
];
